module.exports = {
  apps: [
    {
      name: 'bridge-server',
      script: 'src/lib/bridge-server.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: 'skeleton-qa',
      script: 'src/workers/skeleton-qa.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'deformation-qa',
      script: 'src/workers/deformation-qa.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'finger-alignment',
      script: 'src/workers/finger-alignment.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'joint-centering',
      script: 'src/workers/joint-centering.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'render-preview',
      script: 'src/workers/render-preview.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '1024M',
    },
    {
      name: 'processing',
      script: 'src/workers/processing.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '1024M',
    },
    {
      name: 'generation',
      script: 'src/workers/generation.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'pattern-analysis',
      script: 'src/workers/pattern-analysis.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
    },
    {
      name: 'orchestrator',
      script: 'src/workers/orchestrator.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
    },
    {
      name: 'loop-controller',
      script: 'src/workers/loop-controller.worker.ts',
      cwd: __dirname,
      exec_mode: 'fork',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
    },
  ],
};
