import type { BoneMapEntry, FKChildrenMap, BoneSegment } from '../types/index.js';

/** Maps FBX bone name suffixes to internal joint names (52 bones including all 40 finger bones) */
export const FBX_BONE_MAP: BoneMapEntry[] = [
  // Spine / head
  { suffix: 'Hips',          name: 'hips' },
  { suffix: 'Spine',         name: 'spine_joint' },
  { suffix: 'Spine1',        name: 'spine1_joint' },
  { suffix: 'Spine2',        name: 'spine2_joint' },
  { suffix: 'Neck',          name: 'neck' },
  { suffix: 'Head',          name: 'head' },
  // Collars
  { suffix: 'LeftShoulder',  name: 'l_collar' },
  { suffix: 'RightShoulder', name: 'r_collar' },
  // Left arm
  { suffix: 'LeftArm',       name: 'l_shoulder' },
  { suffix: 'LeftForeArm',   name: 'l_elbow' },
  { suffix: 'LeftHand',      name: 'l_wrist' },
  // Left fingers
  { suffix: 'LeftHandThumb1',  name: 'l_thumb1' },
  { suffix: 'LeftHandThumb2',  name: 'l_thumb2' },
  { suffix: 'LeftHandThumb3',  name: 'l_thumb3' },
  { suffix: 'LeftHandThumb4',  name: 'l_thumb4' },
  { suffix: 'LeftHandIndex1',  name: 'l_index1' },
  { suffix: 'LeftHandIndex2',  name: 'l_index2' },
  { suffix: 'LeftHandIndex3',  name: 'l_index3' },
  { suffix: 'LeftHandIndex4',  name: 'l_index4' },
  { suffix: 'LeftHandMiddle1', name: 'l_mid_knuckle' },
  { suffix: 'LeftHandMiddle2', name: 'l_middle2' },
  { suffix: 'LeftHandMiddle3', name: 'l_middle3' },
  { suffix: 'LeftHandMiddle4', name: 'l_middle4' },
  { suffix: 'LeftHandRing1',   name: 'l_ring1' },
  { suffix: 'LeftHandRing2',   name: 'l_ring2' },
  { suffix: 'LeftHandRing3',   name: 'l_ring3' },
  { suffix: 'LeftHandRing4',   name: 'l_ring4' },
  { suffix: 'LeftHandPinky1',  name: 'l_pinky1' },
  { suffix: 'LeftHandPinky2',  name: 'l_pinky2' },
  { suffix: 'LeftHandPinky3',  name: 'l_pinky3' },
  { suffix: 'LeftHandPinky4',  name: 'l_pinky4' },
  // Left leg
  { suffix: 'LeftUpLeg',     name: 'l_hip' },
  { suffix: 'LeftLeg',       name: 'l_knee' },
  { suffix: 'LeftFoot',      name: 'l_ankle' },
  { suffix: 'LeftToeBase',   name: 'l_toe' },
  // Right arm
  { suffix: 'RightArm',      name: 'r_shoulder' },
  { suffix: 'RightForeArm',  name: 'r_elbow' },
  { suffix: 'RightHand',     name: 'r_wrist' },
  // Right fingers
  { suffix: 'RightHandThumb1',  name: 'r_thumb1' },
  { suffix: 'RightHandThumb2',  name: 'r_thumb2' },
  { suffix: 'RightHandThumb3',  name: 'r_thumb3' },
  { suffix: 'RightHandThumb4',  name: 'r_thumb4' },
  { suffix: 'RightHandIndex1',  name: 'r_index1' },
  { suffix: 'RightHandIndex2',  name: 'r_index2' },
  { suffix: 'RightHandIndex3',  name: 'r_index3' },
  { suffix: 'RightHandIndex4',  name: 'r_index4' },
  { suffix: 'RightHandMiddle1', name: 'r_mid_knuckle' },
  { suffix: 'RightHandMiddle2', name: 'r_middle2' },
  { suffix: 'RightHandMiddle3', name: 'r_middle3' },
  { suffix: 'RightHandMiddle4', name: 'r_middle4' },
  { suffix: 'RightHandRing1',   name: 'r_ring1' },
  { suffix: 'RightHandRing2',   name: 'r_ring2' },
  { suffix: 'RightHandRing3',   name: 'r_ring3' },
  { suffix: 'RightHandRing4',   name: 'r_ring4' },
  { suffix: 'RightHandPinky1',  name: 'r_pinky1' },
  { suffix: 'RightHandPinky2',  name: 'r_pinky2' },
  { suffix: 'RightHandPinky3',  name: 'r_pinky3' },
  { suffix: 'RightHandPinky4',  name: 'r_pinky4' },
  // Right leg
  { suffix: 'RightUpLeg',    name: 'r_hip' },
  { suffix: 'RightLeg',      name: 'r_knee' },
  { suffix: 'RightFoot',     name: 'r_ankle' },
  { suffix: 'RightToeBase',  name: 'r_toe' },
];

/** Full FK hierarchy including all finger chains */
export const FK_CHILDREN: FKChildrenMap = {
  'hips': ['spine_joint', 'l_hip', 'r_hip'],
  'spine_joint': ['spine1_joint'],
  'spine1_joint': ['spine2_joint'],
  'spine2_joint': ['neck', 'l_collar', 'r_collar'],
  'neck': ['head'], 'head': [],
  'l_collar': ['l_shoulder'], 'r_collar': ['r_shoulder'],
  'l_hip': ['l_knee'], 'r_hip': ['r_knee'],
  'l_knee': ['l_ankle'], 'r_knee': ['r_ankle'],
  'l_ankle': ['l_toe'], 'r_ankle': ['r_toe'], 'l_toe': [], 'r_toe': [],
  'l_shoulder': ['l_elbow'], 'r_shoulder': ['r_elbow'],
  'l_elbow': ['l_wrist'], 'r_elbow': ['r_wrist'],
  'l_wrist': ['l_mid_knuckle', 'l_thumb1', 'l_index1', 'l_ring1', 'l_pinky1'],
  'r_wrist': ['r_mid_knuckle', 'r_thumb1', 'r_index1', 'r_ring1', 'r_pinky1'],
  'l_thumb1': ['l_thumb2'], 'l_thumb2': ['l_thumb3'], 'l_thumb3': ['l_thumb4'], 'l_thumb4': [],
  'l_index1': ['l_index2'], 'l_index2': ['l_index3'], 'l_index3': ['l_index4'], 'l_index4': [],
  'l_mid_knuckle': ['l_middle2'], 'l_middle2': ['l_middle3'], 'l_middle3': ['l_middle4'], 'l_middle4': [],
  'l_ring1': ['l_ring2'], 'l_ring2': ['l_ring3'], 'l_ring3': ['l_ring4'], 'l_ring4': [],
  'l_pinky1': ['l_pinky2'], 'l_pinky2': ['l_pinky3'], 'l_pinky3': ['l_pinky4'], 'l_pinky4': [],
  'r_thumb1': ['r_thumb2'], 'r_thumb2': ['r_thumb3'], 'r_thumb3': ['r_thumb4'], 'r_thumb4': [],
  'r_index1': ['r_index2'], 'r_index2': ['r_index3'], 'r_index3': ['r_index4'], 'r_index4': [],
  'r_mid_knuckle': ['r_middle2'], 'r_middle2': ['r_middle3'], 'r_middle3': ['r_middle4'], 'r_middle4': [],
  'r_ring1': ['r_ring2'], 'r_ring2': ['r_ring3'], 'r_ring3': ['r_ring4'], 'r_ring4': [],
  'r_pinky1': ['r_pinky2'], 'r_pinky2': ['r_pinky3'], 'r_pinky3': ['r_pinky4'], 'r_pinky4': [],
};

/** Bone segments for rigidity/bend diagnostics: [parent, child] */
export const BONE_SEGMENTS: BoneSegment[] = [
  ['hips', 'l_hip'], ['hips', 'r_hip'],
  ['l_hip', 'l_knee'], ['r_hip', 'r_knee'],
  ['l_knee', 'l_ankle'], ['r_knee', 'r_ankle'],
  ['l_ankle', 'l_toe'], ['r_ankle', 'r_toe'],
  ['hips', 'spine_joint'],
  ['spine_joint', 'spine1_joint'],
  ['spine1_joint', 'spine2_joint'],
  ['spine2_joint', 'neck'],
  ['neck', 'head'],
  ['l_shoulder', 'l_elbow'], ['r_shoulder', 'r_elbow'],
  ['l_elbow', 'l_wrist'], ['r_elbow', 'r_wrist'],
];

/** Primary child for each joint — the bone segment that joint CONTROLS */
export const JOINT_PRIMARY_CHILD: { [joint: string]: string } = {
  'hips': 'spine_joint',
  'spine_joint': 'spine1_joint',
  'spine1_joint': 'spine2_joint',
  'spine2_joint': 'neck',
  'neck': 'head',
  'l_collar': 'l_shoulder', 'r_collar': 'r_shoulder',
  'l_hip': 'l_knee', 'r_hip': 'r_knee',
  'l_knee': 'l_ankle', 'r_knee': 'r_ankle',
  'l_ankle': 'l_toe', 'r_ankle': 'r_toe',
  'l_shoulder': 'l_elbow', 'r_shoulder': 'r_elbow',
  'l_elbow': 'l_wrist', 'r_elbow': 'r_wrist',
};
